services:
  - type: web
    name: exchange-rates-web
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn exchange_rates.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: exchange-rates-db
          property: connectionString
      - key: REDIS_URL
        value: redis://default:YOUR_REDIS_URL
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: exchange-rates-db
    plan: free
